-- Baseline schema for the order-service domain.
-- Column names follow Spring's snake_case PhysicalNamingStrategy.
-- Uses portable types so the same script runs on PostgreSQL and H2 (tests).

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE customers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    phone       VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE addresses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers (id),
    type        VARCHAR(255) NOT NULL,
    street      VARCHAR(255) NOT NULL,
    city        VARCHAR(255) NOT NULL,
    state       VARCHAR(255),
    postal_code VARCHAR(255) NOT NULL,
    country     VARCHAR(255) NOT NULL
);

CREATE TABLE products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku            VARCHAR(255) NOT NULL UNIQUE,
    name           VARCHAR(255) NOT NULL,
    description    VARCHAR(2000),
    price          NUMERIC(12, 2) NOT NULL,
    stock_quantity INTEGER NOT NULL,
    category_id    BIGINT NOT NULL REFERENCES categories (id),
    version        BIGINT
);

CREATE TABLE purchase_orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(255) NOT NULL UNIQUE,
    customer_id  BIGINT NOT NULL REFERENCES customers (id),
    status       VARCHAR(255) NOT NULL,
    total_amount NUMERIC(14, 2) NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE order_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT NOT NULL REFERENCES purchase_orders (id),
    product_id BIGINT NOT NULL REFERENCES products (id),
    quantity   INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    line_total NUMERIC(14, 2) NOT NULL
);

CREATE TABLE payments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT NOT NULL UNIQUE REFERENCES purchase_orders (id),
    amount         NUMERIC(14, 2) NOT NULL,
    method         VARCHAR(255) NOT NULL,
    status         VARCHAR(255) NOT NULL,
    transaction_id VARCHAR(255),
    paid_at        TIMESTAMP WITH TIME ZONE
);

CREATE TABLE shipments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT NOT NULL UNIQUE REFERENCES purchase_orders (id),
    shipping_address_id BIGINT NOT NULL REFERENCES addresses (id),
    status              VARCHAR(255) NOT NULL,
    carrier             VARCHAR(255),
    tracking_number     VARCHAR(255),
    shipped_at          TIMESTAMP WITH TIME ZONE,
    delivered_at        TIMESTAMP WITH TIME ZONE
);
